# Generated by Django 4.2.5 on 2023-10-21 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('teams_id', models.IntegerField()),
                ('conditions', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=list, size=None)),
                ('game_round', models.IntegerField()),
            ],
        ),
    ]
