# Generated by Django 4.2.5 on 2023-10-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('first_user_id', models.IntegerField()),
                ('second_user_id', models.IntegerField()),
            ],
        ),
    ]
